/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FraudAlertsRouteImport } from './routes/fraud-alerts'
import { Route as DecisionSimulatorRouteImport } from './routes/decision-simulator'
import { Route as DatasetManagerRouteImport } from './routes/dataset-manager'
import { Route as Customer360RouteImport } from './routes/customer-360'
import { Route as ChurnRiskRouteImport } from './routes/churn-risk'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudAlertsRoute = FraudAlertsRouteImport.update({
  id: '/fraud-alerts',
  path: '/fraud-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionSimulatorRoute = DecisionSimulatorRouteImport.update({
  id: '/decision-simulator',
  path: '/decision-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetManagerRoute = DatasetManagerRouteImport.update({
  id: '/dataset-manager',
  path: '/dataset-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const Customer360Route = Customer360RouteImport.update({
  id: '/customer-360',
  path: '/customer-360',
  getParentRoute: () => rootRouteImport,
} as any)
const ChurnRiskRoute = ChurnRiskRouteImport.update({
  id: '/churn-risk',
  path: '/churn-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/churn-risk': typeof ChurnRiskRoute
  '/customer-360': typeof Customer360Route
  '/dataset-manager': typeof DatasetManagerRoute
  '/decision-simulator': typeof DecisionSimulatorRoute
  '/fraud-alerts': typeof FraudAlertsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/churn-risk': typeof ChurnRiskRoute
  '/customer-360': typeof Customer360Route
  '/dataset-manager': typeof DatasetManagerRoute
  '/decision-simulator': typeof DecisionSimulatorRoute
  '/fraud-alerts': typeof FraudAlertsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/churn-risk': typeof ChurnRiskRoute
  '/customer-360': typeof Customer360Route
  '/dataset-manager': typeof DatasetManagerRoute
  '/decision-simulator': typeof DecisionSimulatorRoute
  '/fraud-alerts': typeof FraudAlertsRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/churn-risk'
    | '/customer-360'
    | '/dataset-manager'
    | '/decision-simulator'
    | '/fraud-alerts'
    | '/login'
    | '/reports'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/churn-risk'
    | '/customer-360'
    | '/dataset-manager'
    | '/decision-simulator'
    | '/fraud-alerts'
    | '/login'
    | '/reports'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/churn-risk'
    | '/customer-360'
    | '/dataset-manager'
    | '/decision-simulator'
    | '/fraud-alerts'
    | '/login'
    | '/reports'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChurnRiskRoute: typeof ChurnRiskRoute
  Customer360Route: typeof Customer360Route
  DatasetManagerRoute: typeof DatasetManagerRoute
  DecisionSimulatorRoute: typeof DecisionSimulatorRoute
  FraudAlertsRoute: typeof FraudAlertsRoute
  LoginRoute: typeof LoginRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-alerts': {
      id: '/fraud-alerts'
      path: '/fraud-alerts'
      fullPath: '/fraud-alerts'
      preLoaderRoute: typeof FraudAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-simulator': {
      id: '/decision-simulator'
      path: '/decision-simulator'
      fullPath: '/decision-simulator'
      preLoaderRoute: typeof DecisionSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset-manager': {
      id: '/dataset-manager'
      path: '/dataset-manager'
      fullPath: '/dataset-manager'
      preLoaderRoute: typeof DatasetManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-360': {
      id: '/customer-360'
      path: '/customer-360'
      fullPath: '/customer-360'
      preLoaderRoute: typeof Customer360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/churn-risk': {
      id: '/churn-risk'
      path: '/churn-risk'
      fullPath: '/churn-risk'
      preLoaderRoute: typeof ChurnRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChurnRiskRoute: ChurnRiskRoute,
  Customer360Route: Customer360Route,
  DatasetManagerRoute: DatasetManagerRoute,
  DecisionSimulatorRoute: DecisionSimulatorRoute,
  FraudAlertsRoute: FraudAlertsRoute,
  LoginRoute: LoginRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
